config/routes.rb
Rails.application.routes.draw do

  resources :students

   namespace :api, :defaults => {:format => 'json'} do
      namespace :v1 do
        resources :students
      end
    end

  resources :notes
  resources :subjects
  resources :courses

  # Root
  root :to => "dashboard#index"  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :subjects, :foreign_key => 'id'
  belongs_to :notes, optional: true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :student, inverse_of: :notes, optional: true
  belongs_to :subject, inverse_of: :notes, optional: true
  belongs_to :course, optional: true
  accepts_nested_attributes_for :student
  accepts_nested_attributes_for :subject
  accepts_nested_attributes_for :course
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :courses, :foreign_key => 'id'
  belongs_to :notes, optional: true
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :notes, :foreign_key => 'id'
  belongs_to :course, optional: true
end

app/controllers/api/base_controller.rb
class Api::BaseController < InheritedResources::Base
  respond_to :xml, :json
end

app/controllers/api/v1/students_controller.rb
module Api
  module V1
    class StudentsController < Api::BaseController

      def index
        
        @allS = []
        @students =  Student.all
        @students.each do |s|

          subj = []
          notes = Note.where(:student_id => s.id).to_a
          s.courses.each do |c|
            subj.push(c.subjects.to_a)
          end
          obj = {"student" => s, "Courses" => s.courses.to_a, "Sunjects" => subj, "Notes" => notes}
          
          @allS.push(obj)
        end
        p "@allS"
        p @allS
        render :json=> {:students =>@allS }, :status => :ok
      end



    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @course =  Course.all
    respond_to do |format|
      format.html
    end
  end

  def show
    @course = Course.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  def new
    @course = Course.new
    respond_to do |format|
      format.html
    end
  end

  def edit
    @course = Course.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  def create
    @course =  Course.new(course_params)
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'El Curso ha sido creado exitosamente.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    @course = Course.find(params[:id])
    respond_to do |format|
      if @course.update_attributes(course_params)
        format.html { redirect_to @course, notice: 'El curso ha sido actualizado exitosamente.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  private

def set_course
  @course = Course.find(params[:id])
end

def course_params
  params.require(:course).permit!
end


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def index
    @notes =  Note.all
    respond_to do |format|
      format.html
    end
  end

  def show
    @note = Note.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  def new
    @note = Note.new
    respond_to do |format|
      format.html
    end
  end


  def create
    
    @student = Student.find(params[:note][:student])
    @course = Course.find(params[:note][:course])
    @subject = Subject.find(params[:note][:subject])
    @value = params[:note][:value]
    @note =  Note.new

    if validate_note(@value) == true
      @note.student = @student
      @note.course = @course
      @note.subject = @subject 
      @note.value = @value 

      respond_to do |format|
        if @note.save
          format.html { redirect_to @note }
        else
          format.html { render action: "new" }
        end
      end
    else 

    flash[:notice] = "!!!!! Error de Validacion la nota ingresada es: #{@value} la hora es: #{@now} los minutos son #{@minutes} la validacion es #{@validation} "
    render action: "new"
    end
  end

  def validate_note(value)
    @now = Time.now
    @minutes = @now.strftime('%M').to_i
    @tStudents = Student.all.count.to_i

    @validation = @minutes + @tStudents

    if value.to_i < @validation
      return true
    else 
      return false 
    end
  end

  private

def set_course
  @note = Note.find(params[:id])
end

def course_params
  params.require(:note).permit!
end


end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students =  Student.all
    respond_to do |format|
      format.html
    end
  end

  def show
    @student = Student.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  def new
    @student = Student.new
    respond_to do |format|
      format.html
    end
  end


  def create
    @student =  Student.new(student_params)
    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'El estudiante ha sido creado exitosamente.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def edit
    @student = Student.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  def update
    @student = Student.find(params[:id])
    respond_to do |format|
      if @student.update_attributes(student_params)
        format.html { redirect_to @student, notice: 'El estudiente ha sido actualizado exitosamente.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  private

def set_student
  @student = Student.find(params[:id])
end

def student_params
  params.require(:student).permit!
end


end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  def index
    @subjects =  Subject.all
    respond_to do |format|
      format.html
    end
  end

  def show
    @subject = Subject.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  def new
    @subject = Subject.new
    respond_to do |format|
      format.html
    end
  end


  def create
    @subject =  Subject.new(subject_params)
    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'La materia ha sido creado exitosamente.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  private

def set_course
  @subject = Subject.find(params[:id])
end

def subject_params
  params.require(:subject).permit!
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/courses/_fields.html.slim
.card.col.s12
	.col.s4
		= f.input :name, :label => 'Nombre'
		= f.association :subjects, :collection => Subject.all, :input_html => { :multiple => false } 

app/views/courses/_subject_fields.html.slim
.card.col.s12
	.col.s4
		= f.input :name, :label => 'Materia'
  

app/views/courses/edit.html.slim
|Editar Curso #{@course.name}
.row
		= simple_form_for(@course) do |n|
			.row
				.col.s12
						.card.horizontal.grey.lighten-2
							.card-stacked
								.card-content.blue-grey.lighten-5
									= render 'fields', f: n
								.card-action
									= submit_tag 'Actualizar', class: 'btn btn-primary'

app/views/courses/index.html.slim
.table-light
  .table-header
    .table-caption
      | Lista Cursos
  table.table.table-bordered.table-striped
    thead
      tr
        th Nombre

    tbody
      - @course.each do |c|
      	tr
          td
            strong = link_to c.name, course_path(c)


  .table-footer
		= link_to 'New course', new_course_path, class: 'btn btn-primary'
		br
		= link_to "Ir a Home", root_path

app/views/courses/new.html.slim
|  Nuevo Curso
.row
		= simple_form_for(@course) do |f| 
			.col.s12
					.card.horizontal.grey.lighten-2
						.card-stacked
							.card-content.blue-grey.lighten-5
								= render 'fields', f: f
							.card-action
								= submit_tag 'Crear Curso', class: 'btn btn-primary'

app/views/courses/show.html.slim
.container id="main-container"
	.card-panel.cyan.lighten-4
		h5 id="title-panel-text"
			i.material-icons id="title-panel-icon" 
			| #{@course.name}  
		
    .card-action
						= link_to 'Editar', edit_course_path(@course), class: 'btn btn-default' 
						br
						= link_to "Ir a Home", root_path

app/views/dashboard/index.html.slim
|   Institucion Educativa DevCode

ul#slide-out.side-nav.fixed
    = content_tag :li, link_to('students', students_path) 
    = content_tag :li, link_to('courses', courses_path) 
    = content_tag :li, link_to('subjects', subjects_path) 
    = content_tag :li, link_to('notes', notes_path) 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevCode</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_fields.html.slim
.card.col.s12
	.col.s4
		= f.input :student, :collection => Student.all
		= f.input :course, :collection => Course.all
		= f.input :subject, :collection => Subject.all
		= f.input :value, :label => 'Valor'

app/views/notes/edit.html.slim
|Editar nota #{@note.name}
.row
		= simple_form_for(@note) do |n|
			.row
				.col.s12
						.card.horizontal.grey.lighten-2
							.card-stacked
								.card-content.blue-grey.lighten-5
									= render 'fields', f: n
								.card-action
									= submit_tag 'Actualizar', class: 'btn btn-primary'

app/views/notes/index.html.slim
.table-light
  .table-header
    .table-caption
      | Lista Notas
  table.table.table-bordered.table-striped
    thead
      tr
        th Estudiante
        th Curso
        th Materia
        th Valor
    tbody
      - @notes.each do |n|
        tr
          td
            = Student.find(n.student_id).name if n.student_id
          td
            = Course.find(n.course_id).name if n.course_id
          td
            = Subject.find(n.subject_id).name if n.subject_id
          td
            strong = n.value
  .table-footer
		= link_to 'New note', new_note_path, class: 'btn btn-primary'
		br
		= link_to "Ir a Home", root_path

app/views/notes/new.html.slim
|  Nueva Nota

- if flash[:notice]
  div.notice
		= flash[:notice] 

.row
		= simple_form_for(@note) do |f| 
			.col.s12
					.card.horizontal.grey.lighten-2
						.card-stacked
							.card-content.blue-grey.lighten-5
								= render 'fields', f: f
							.card-action
								= submit_tag 'Crear Nota', class: 'btn btn-primary'

app/views/notes/show.html.slim
table 
  tr
    th Estudiante
    th Curso
    th Materia
    th Valor
  tr
    td = Student.find(@note.student_id).name
    td = Course.find(@note.course_id).name
    td = Subject.find(@note.subject_id).name
    td = @note.value

.card-action
						= link_to 'Editar', edit_note_path(@note), class: 'btn btn-default' 
						br
						= link_to "Ir a Home", root_path

app/views/students/_fields.html.slim
.card.col.s12
	.col.s4
		= f.input :name, :label => 'Nombre'
		= f.association :courses, collection: Course.all, :input_html => { :multiple => false } 

app/views/students/edit.html.slim
|Editar Estudiente #{@student.name}
.row
		= simple_form_for(@student) do |n|
			.row
				.col.s12
						.card.horizontal.grey.lighten-2
							.card-stacked
								.card-content.blue-grey.lighten-5
									= render 'fields', f: n
								.card-action
									= submit_tag 'Actualizar', class: 'btn btn-primary'

app/views/students/index.html.slim
.table-light
  .table-header
    .table-caption
      | Lista Estudiantes
  table.table.table-bordered.table-striped
    thead
      tr
        th Nombre

    tbody
      - @students.each do |s|
      	tr
          td
            strong = link_to s.name, student_path(s)


  .table-footer
		= link_to 'New Student', new_student_path, class: 'btn btn-primary'
		br
		= link_to "Ir a Home", root_path

app/views/students/new.html.slim
|  Nuevo Estudiante
.row
		= simple_form_for(@student) do |f| 
			.col.s12
					.card.horizontal.grey.lighten-2
						.card-stacked
							.card-content.blue-grey.lighten-5
								= render 'fields', f: f
							.card-action
								= submit_tag 'Crear estudiante', class: 'btn btn-primary'

app/views/students/show.html.slim
.container id="main-container"
	.card-panel.cyan.lighten-4
		h5 id="title-panel-text"
			i.material-icons id="title-panel-icon" 
			| #{@student.name}  
    p Cursos:

    - @student.courses.all.each do |c|
       = c.name
  		
    .card-action
						= link_to 'Editar', edit_student_path(@student), class: 'btn btn-default' 
						br
						= link_to "Ir a Home", root_path

app/views/subjects/_fields.html.slim
.card.col.s12
	.col.s4
		= f.input :name, :label => 'Nombre'

app/views/subjects/index.html.slim
.table-light
  .table-header
    .table-caption
      | Lista Materias
  table.table.table-bordered.table-striped
    thead
      tr
        th Nombre

    tbody
      - @subjects.each do |s|
      	tr
          td
            strong = link_to s.name, subjects_path(s)


  .table-footer
		= link_to 'New subjects', new_subject_path, class: 'btn btn-primary'
		br
		= link_to "Ir a Home", root_path

app/views/subjects/new.html.slim
|  Nueva Materia
.row
		= simple_form_for(@subject) do |f| 
			.col.s12
					.card.horizontal.grey.lighten-2
						.card-stacked
							.card-content.blue-grey.lighten-5
								= render 'fields', f: f
							.card-action
								= submit_tag 'Crear Materia', class: 'btn btn-primary'

app/views/subjects/show.html.slim
.container id="main-container"
	.card-panel.cyan.lighten-4
		h5 id="title-panel-text"
			i.material-icons id="title-panel-icon" 
			| #{@subject.name}  
		
    .card-action
						= link_to 'Editar', edit_subject_path(@subject), class: 'btn btn-default' 
						br
						= link_to "Ir a Home", root_path
 